apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "xl-release.fullname" . }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
