apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "xl-release.fullname" . }}-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      product: "xl-release"
      contents: "data"
